$background = rgb(101417)
$foreground = rgb(e0e3e8)
$color0 = rgb(101417)
$color1 = rgb(ffb4ab)
$color2 = rgb(95cdf8)
$color3 = rgb(cfc0e8)
$color4 = rgb(cae6ff)
$color5 = rgb(d3e5f5)
$color6 = rgb(b7c9d9)
$color7 = rgb(e0e3e8)
$color8 = rgb(363a3e)
$color9 = rgb(ffb4ab)
$color10 = rgb(95cdf8)
$color11 = rgb(cfc0e8)
$color12 = rgb(cae6ff)
$color13 = rgb(d3e5f5)
$color14 = rgb(b7c9d9)
$color15 = rgb(e0e3e8)
