$primary = rgb(7ad4df)
$surface = rgb(101415)
$secondary = rgb(abcdd1)
$error = rgb(ffb4ab)
$tertiary = rgb(e0b7fa)
$surface_lowest = rgb(0a0f10)

general {
    col.active_border = $primary
    col.inactive_border = $surface
}

group {
    col.border_active = $secondary
    col.border_inactive = $surface
    col.border_locked_active = $error
    col.border_locked_inactive = $surface

    groupbar {
        col.active = $secondary
        col.inactive = $surface
        col.locked_active = $error
        col.locked_inactive = $surface
    }
}
