color0 #101417
color1 #ffb4ab
color2 #cfc0e8
color3 #b7c9d9
color4 #95cdf8
color5 #95cdf8
color6 #b7c9d9
color7 #e0e3e8
color8 #8b9198
color9 #b7c9d9
color10 #4c4162
color11 #1c2024
color12 #004b6f
color13 #cae6ff
color14 #41474d
color15 #e0e3e8

cursor #95cdf8
cursor_text_color #e0e3e8

foreground            #e0e3e8
background            #101417
selection_foreground  #22323f
selection_background  #b7c9d9
url_color             #95cdf8
