color0 #101415
color1 #ffb4ab
color2 #7ad4df
color3 #abcdd1
color4 #e0b7fa
color5 #7ad4df
color6 #abcdd1
color7 #dfe3e3
color8 #889394
color9 #ffb4ab
color10 #7ad4df
color11 #abcdd1
color12 #e0b7fa
color13 #7ad4df
color14 #abcdd1
color15 #dfe3e3

cursor                #dfe3e3
cursor_text_color     #101415
background            #101415
foreground            #dfe3e3
selection_foreground  #bdc9ca
selection_background  #3e494a
active_border_color   #7ad4df
inactive_border_color #3e494a
url_color             #7ad4df

active_tab_foreground   #00363b
active_tab_background   #7ad4df
inactive_tab_foreground #bdc9ca
inactive_tab_background #3e494a
cursor_trail_color      #bdc9ca
