# ----------------------------------------------------- 
# Autostart
# ----------------------------------------------------- 

# launch quickshell and lock the screen
exec-once = qs -c noctalia-shell

# Setup XDG for screen sharing
exec-once = ~/dotfiles/hypr/scripts/xdg.sh

# Load GTK settings
exec-once = ~/dotfiles/gtk/gtk.sh

# Load cliphist history
exec-once = wl-paste --watch cliphist store

# Load gnome polkit agent
exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1

# Load udiskie
exec-once = udiskie --appindicator -t
